name: actions-demo-workflow
on: [push]
jobs:
        actions-demo-jobs:
                runs-on: ubuntu-latest
                env:
                        Tag: 0
                        CR_PAT: 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
                steps:
                        - uses: actions/checkout@v2
                        - name: generate docker tag
                          id: tag
                          run: echo "::set-output name=date::$(date +'%Y%m%d%M%S')"

                        - name: generate docker tag2
                          run: echo "Tag=$(date +'%Y%m%d%M%S')" >> $GITHUB_ENV
                        - name: build docker image
                          run: |
                                  cd ActionsDemo
                                  docker build . -t actionsdemo:${{steps.tag.outputs.date}}
                        - name: build docker image 2
                          run: |
                                  cd ActionsDemo
                                  docker build . -t actionsdemo:${{env.Tag}}

                        - name: docker login
                          run: |
                                  echo $CR_PAT
                                  echo $CR_PAT | docker login ghcr.io -u jithin.veedu@capgemini.com --password-stdin

                        - name: docker push
                          run: docker push ghcr.io/jithinkveedu/actionsdemo:${{env.Tag}}
