name: actions-demo-workflow
on: [push]

permissions:
        packages: write


jobs:
        actions-demo-build-push:
                runs-on: ubuntu-latest
                outputs:
                        IMAGE: ${{steps.buildandpush.output.IMAGENAME}}
                        output2: ${{ steps.step2.outputs.test }}
                env:
                        Tag: 0
                        CR_PAT: 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
                        REGISTRY: ghcr.io
                        ACTOR: ${{github.actor}}
                        TOKEN: ${{secrets.GITHUB_TOKEN}}
                steps:
                        - uses: actions/checkout@v2
                        - name: generate docker tag
                          id: tag
                          run: echo "::set-output name=date::$(date +'%Y%m%d%M%S')"

                        - name: generate docker tag2
                          run: echo "Tag=$(date +'%Y%m%d%M%S')" >> $GITHUB_ENV
                        - name: build docker image
                          run: |
                                  cd ActionsDemo
                                  docker build . -t actionsdemo:${{steps.tag.outputs.date}}
                        - name: build docker image 2
                          run: |
                                  cd ActionsDemo
                                  docker build . -t $REGISTRY/$ACTOR/actionsdemo:${{env.Tag}} 
                                  
                        - name: set out
                          id: buildandpush
                          run:  echo "::set-output name=IMAGENAME::hello"                          

                        - id: step2
                          run: echo "::set-output name=test::world"

                        - name: docker login
                          run: echo $TOKEN | docker login ghcr.io -u $ACTOR --password-stdin

                        - name: docker push
                          run: docker push $REGISTRY/$ACTOR/actionsdemo:${{env.Tag}}
                        - name: login to github package using actions
                          uses: docker/login-action@v1
                          with:
                                  registry: ghcr.io
                                  username: ${{github.actor}}
                                  password: ${{secrets.GITHUB_TOKEN}}


                        
        actions-demo-pull-deploy:
                needs: actions-demo-build-push
                runs-on: ubuntu-latest
                environment:
                        name: Production
                steps:
                        - name: get name
                          run: echo ${{needs.actions-demo-build-push.outputs.IMAGE}} ${{needs.actions-demo-build-push.outputs.output2}}
